services:
  front:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
      args:
        BOT_API_URL: ${BOT_API_URL}
    image: ocap-stats-front:latest
    ports:
      - ${PORT}:80
