name: Check lint and build

on:
  push:
    branches: [ dev ]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12

      - name: Install Node.js modules
        run: npm ci

      - name: Run ESLint
        run: npm run lint
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12

      - name: Install Node.js modules
        run: npm ci

      - name: Run webpack build
        run: npm run build
        env:
          BOT_API_URL: ${{ secrets.BOT_API_URL }}
